name: CanIHaveOp
main: me.arns.canihaveop.CanIhaveOp
version: 1.0
author: arns
commands:
   canihaveop:
      description: Do you want op? Just run this command and we will decide.
      usage: /<command>